apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
configMapGenerator:
- name: namespace-annotations-cm
  files:
  - namespace-annotations.sh
  - namespaces.txt
generatorOptions:
  annotations:
     argocd.argoproj.io/sync-wave: "-1"
resources:
- job-namespace-annotations.yaml
patchesStrategicMerge:
  - patch-argocd-application.yaml